# Generated by Django 4.0.2 on 2022-02-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_set',
        ),
        migrations.AddField(
            model_name='card',
            name='folder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cards.folder'),
        ),
        migrations.DeleteModel(
            name='CardSet',
        ),
    ]
